services:
  - type: web
    name: searxng
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SEARXNG_BASE_URL
        sync: false
      - key: SEARXNG_SECRET_KEY
        generateValue: true
