services:
  - type: web
    name: searxng
    runtime: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: SEARXNG_BASE_URL
        value: "https://moteur-server-xng.onrender.com"
      - key: SEARXNG_SECRET_KEY
        generateValue: true
